#!/usr/bin/env python
"""
Script description

Author: Peter Pakos <peter.pakos@wandisco.com>
"""

from __future__ import print_function
import argparse
import os
import sys


class Main(object):
    """
    Main class
    """

    def __init__(self):
        """
        Constructor
        """
        self._name = os.path.basename(sys.argv[0])
        self._version = '1.0.0'
        self._args = self._parse_args()

    def __del__(self):
        """
        Destructor
        """
        pass

    def _parse_args(self):
        """
        Parse command line arguments
        """
        parser = argparse.ArgumentParser(description='Script description')
        parser.add_argument('--version', action='version', version='%s %s' %
                            (self._name, self._version))

        return parser.parse_args()

    @staticmethod
    def die(message=None, code=1):
        """
        Gracefully exit the program
        """
        if message:
            print(message, file=sys.stderr)
        exit(code)

    @staticmethod
    def run():
        """
        Execute main code
        """
        print('Hello World!')


if __name__ == '__main__':
    try:
        main = Main()  # pylint: disable-msg=C0103
        main.run()
    except KeyboardInterrupt:
        print('\nCancelling...')
